//this file is part of notepad++
//Copyright (C)2022 Don HO <don.h@free.fr>
//
//This program is free software; you can redistribute it and/or
//modify it under the terms of the GNU General Public License
//as published by the Free Software Foundation; either
//version 2 of the License, or (at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with this program; if not, write to the Free Software
//Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

#ifndef NOTEPAD_PLUS_MSGS_H
#define NOTEPAD_PLUS_MSGS_H

#include <windows.h>

enum LangType {
	L_TEXT, L_PHP , L_C, L_CPP, L_CS, L_OBJC, L_JAVA, L_RC,
	L_HTML, L_XML, L_MAKEFILE, L_PASCAL, L_BATCH, L_INI, L_ASCII, L_USER,
	L_ASP, L_SQL, L_VB, L_JS, L_CSS, L_PERL, L_PYTHON, L_LUA,
	L_TEX, L_FORTRAN, L_BASH, L_FLASH, L_NSIS, L_TCL, L_LISP, L_SCHEME,
	L_ASM, L_DIFF, L_PROPS, L_PS, L_RUBY, L_SMALLTALK, L_VHDL, L_KIX, L_AU3,
	L_CAML, L_ADA, L_VERILOG, L_MATLAB, L_HASKELL, L_INNO, L_SEARCHRESULT,
	L_CMAKE, L_YAML, L_COBOL, L_GUI4CLI, L_D, L_POWERSHELL, L_R, L_JSP,
	L_COFFEESCRIPT, L_JSON, L_JAVASCRIPT, L_FORTRAN_77, L_BAANC, L_SREC,
	L_IHEX, L_TEHEX, L_SWIFT,
	L_ASN1, L_AVS, L_BLITZBASIC, L_PUREBASIC, L_FREEBASIC,
	L_CSOUND, L_ERLANG, L_ESCRIPT, L_FORTH, L_LATEX,
	L_MMIXAL, L_NIMROD, L_NNCRONTAB, L_OSCRIPT, L_REBOL,
	L_REGISTRY, L_RUST, L_SPICE, L_TXT2TAGS, L_VISUALPROLOG, L_TYPESCRIPT,
	L_EXTERNAL
};

enum winVer {
	WV_UNKNOWN, WV_WIN32S, WV_95, WV_98, WV_ME, WV_NT, WV_W2K,
	WV_XP, WV_S2003, WV_XPX64, WV_VISTA, WV_WIN7, WV_WIN8, WV_WIN81, WV_WIN10, WV_WIN11
};

// NPPM_GETCURRENTSCINTILLA
#define NPPMSG  (WM_USER + 1000)
#define NPPM_GETCURRENTSCINTILLA  (NPPMSG + 4)
#define NPPM_GETCURRENTLANGTYPE   (NPPMSG + 5)
#define NPPM_SETCURRENTLANGTYPE   (NPPMSG + 6)

#define NPPM_GETNBOPENFILES       (NPPMSG + 7)

#define NPPM_GETOPENFILENAMES     (NPPMSG + 8)

#define NPPM_MODELESSDIALOG       (NPPMSG + 12)
#define MODELESSDIALOGADD      0
#define MODELESSDIALOGREMOVE   1

#define NPPM_GETNBSESSIONFILES    (NPPMSG + 13)
#define NPPM_GETSESSIONFILES      (NPPMSG + 14)
#define NPPM_SAVESESSION          (NPPMSG + 15)
#define NPPM_SAVECURRENTSESSION   (NPPMSG + 16)

#define NPPM_GETOPENFILENAMESPRIMARY   (NPPMSG + 17)
#define NPPM_GETOPENFILENAMESSECOND    (NPPMSG + 18)

#define NPPM_CREATESCINTILLAHANDLE     (NPPMSG + 20)
#define NPPM_DESTROYSCINTILLAHANDLE    (NPPMSG + 21)
#define NPPM_GETNBUSERLANG             (NPPMSG + 22)

#define NPPM_GETCURRENTDOCINDEX        (NPPMSG + 23)
#define MAIN_VIEW 0
#define SUB_VIEW 1

#define NPPM_SETSTATUSBAR              (NPPMSG + 24)
#define STATUSBAR_DOC_TYPE    0
#define STATUSBAR_DOC_SIZE    1
#define STATUSBAR_CUR_POS     2
#define STATUSBAR_EOF_FORMAT  3
#define NPPM_GETMENUHANDLE             (NPPMSG + 25)
#define NPPPLUGINMENU      0

#define NPPM_ENCODESCI                 (NPPMSG + 26)
#define NPPM_DECODESCI                 (NPPMSG + 27)

#define NPPM_ACTIVATEDOC               (NPPMSG + 28)

#define NPPM_LAUNCHFINDINFILESDLG      (NPPMSG + 29)

#define NPPM_DMMSHOW                   (NPPMSG + 30)
#define NPPM_DMMHIDE                   (NPPMSG + 31)
#define NPPM_DMMUPDATEDISPINFO         (NPPMSG + 32)
#define NPPM_DMMREGASDCKDLG            (NPPMSG + 33)

#define NPPM_LOADSESSION               (NPPMSG + 34)

#define NPPM_DMMVIEWOTHERTAB           (NPPMSG + 35)

#define NPPM_RELOADFILE                (NPPMSG + 36)

#define NPPM_SWITCHTOFILE              (NPPMSG + 37)

#define NPPM_SAVECURRENTFILE           (NPPMSG + 38)
#define NPPM_SAVEALLFILES              (NPPMSG + 39)

#define NPPM_SETMENUITEMCHECK          (NPPMSG + 40)

#define NPPM_ADDTOOLBARICON_DEPRECATED (NPPMSG + 41)
#define NPPM_GETWINDOWSVERSION         (NPPMSG + 42)

#define NPPM_DMMGETPLUGINHWNDBYNAME    (NPPMSG + 43)

#define NPPM_MAKECURRENTBUFFERDIRTY    (NPPMSG + 44)

#define NPPM_GETENABLETHEMETEXTUREFUNC (NPPMSG + 45)

#define NPPM_GETPLUGINSCONFIGDIR       (NPPMSG + 46)

#define NPPM_MSGTOPLUGIN               (NPPMSG + 47)

#define NPPM_MENUCOMMAND               (NPPMSG + 48)

#define NPPM_TRIGGERTABBARCONTEXTMENU  (NPPMSG + 49)

#define NPPM_GETNPPVERSION             (NPPMSG + 50)

#define NPPM_HIDETABBAR                (NPPMSG + 51)

#define NPPM_ISTABBARHIDDEN            (NPPMSG + 52)

#define NPPM_GETPOSFROMBUFFERID        (NPPMSG + 57)
#define NPPM_GETFULLPATHFROMBUFFERID   (NPPMSG + 58)
#define NPPM_GETBUFFERIDFROMPOS        (NPPMSG + 59)

#define NPPM_GETCURRENTBUFFERID        (NPPMSG + 60)
#define NPPM_RELOADBUFFERID            (NPPMSG + 61)

#define NPPM_GETBUFFERLANGTYPE         (NPPMSG + 64)
#define NPPM_SETBUFFERLANGTYPE         (NPPMSG + 65)

#define NPPM_GETBUFFERENCODING         (NPPMSG + 66)
#define NPPM_SETBUFFERENCODING         (NPPMSG + 67)

#define NPPM_GETBUFFERFORMAT           (NPPMSG + 68)
#define NPPM_SETBUFFERFORMAT           (NPPMSG + 69)

#define NPPM_HIDETOOLBAR               (NPPMSG + 70)
#define NPPM_ISTOOLBARHIDDEN           (NPPMSG + 71)

#define NPPM_HIDEMENU                  (NPPMSG + 72)
#define NPPM_ISMENUHIDDEN              (NPPMSG + 73)

#define NPPM_HIDESTATUSBAR             (NPPMSG + 74)
#define NPPM_ISSTATUSBARHIDDEN         (NPPMSG + 75)

#define NPPM_GETSHORTCUTBYCMDID        (NPPMSG + 76)

#define NPPM_DOOPEN                    (NPPMSG + 77)

#define NPPM_SAVECURRENTFILEAS         (NPPMSG + 78)

#define NPPM_GETCURRENTNATIVELANGENCODING (NPPMSG + 79)

#define NPPM_ALLOCATESUPPORTED         (NPPMSG + 80)
#define NPPM_ALLOCATECMDID             (NPPMSG + 81)
#define NPPM_ALLOCATEMARKER            (NPPMSG + 82)

#define NPPM_GETLANGUAGENAME           (NPPMSG + 83)
#define NPPM_GETLANGUAGEDESC           (NPPMSG + 84)

#define NPPM_SHOWDOCSWITCHER           (NPPMSG + 85)

#define NPPM_ISDOCSWITCHERSHOWN        (NPPMSG + 86)

#define NPPM_GETAPPDATAPLUGINSALLOWED  (NPPMSG + 87)

#define NPPM_GETCURRENTVIEW            (NPPMSG + 88)

#define NPPM_DOCSWITCHERDISABLECOLUMN  (NPPMSG + 89)

#define NPPM_GETEDITORDEFAULTFOREGROUNDCOLOR (NPPMSG + 90)
#define NPPM_GETEDITORDEFAULTBACKGROUNDCOLOR (NPPMSG + 91)

#define NPPM_SETSMOOTHFONT             (NPPMSG + 92)
#define NPPM_SETEDITORBORDEREDGE       (NPPMSG + 93)

#define NPPM_SAVEFILE                  (NPPMSG + 94)

#define NPPM_DISABLEAUTOUPDATE         (NPPMSG + 95)

#define NPPM_REMOVESHORTCUTBYCMDID     (NPPMSG + 96)

#define NPPM_GETPLUGINHOMEPATH         (NPPMSG + 97)

#define NPPM_GETFILENAMEATCURSOR       (NPPMSG + 98)

#define NPPM_GETCURRENTWORD            (NPPMSG + 99)

#define NPPM_GETNPPFULLFILEPATH        (NPPMSG + 100)

#define NPPM_GETCURRENTLINESTR         (NPPMSG + 101)

#define NPPM_GETSETTINGSONCLOUDPATH    (NPPMSG + 102)

#define NPPM_SETLINENUMBERWIDTHMODE    (NPPMSG + 103)

#define NPPM_GETLINENUMBERWIDTHMODE    (NPPMSG + 104)

#define NPPM_ADDTOOLBARICON_FORDARKMODE (NPPMSG + 105)

#define NPPM_GETEXTERNALLEXERAUTOINDENTMODE (NPPMSG + 106)

#define NPPM_SETEXTERNALLEXERAUTOINDENTMODE (NPPMSG + 107)

#define NPPM_ISAUTOINDENTON            (NPPMSG + 108)

#define NPPM_GETCURRENTMACROSTATUS     (NPPMSG + 109)
#define NPPM_ISDARKMODEENABLED         (NPPMSG + 110)

#define NPPM_GETDARKMODECOLORS         (NPPMSG + 111)

#define NPPM_GETCURRENTCMDLINE         (NPPMSG + 112)

#define NPPM_CREATELEXER               (NPPMSG + 113)

#define NPPM_GETBOOKMARKID             (NPPMSG + 114)

#define NPPM_DARKMODESUBCLASSANDTHEME  (NPPMSG + 115)

struct toolbarIconsWithDarkMode {
	HBITMAP	hToolbarBmp;
	HBITMAP	hToolbarIcon;
	HBITMAP	hToolbarIconDarkMode;
};

#define RUNCOMMAND_USER    (WM_USER + 3000)
#define NPPM_GETFULLCURRENTPATH        (RUNCOMMAND_USER + FULL_CURRENT_PATH)
#define NPPM_GETCURRENTDIRECTORY       (RUNCOMMAND_USER + CURRENT_DIRECTORY)
#define NPPM_GETFILENAME               (RUNCOMMAND_USER + FILE_NAME)
#define NPPM_GETNAMEPART               (RUNCOMMAND_USER + NAME_PART)
#define NPPM_GETEXTPART                (RUNCOMMAND_USER + EXT_PART)
#define NPPM_GETCURRENTWORD_BIS        (RUNCOMMAND_USER + CURRENT_WORD)
#define NPPM_GETNPPDIRECTORY           (RUNCOMMAND_USER + NPP_DIRECTORY)
#define NPPM_GETFILENAMEATCURSOR_BIS   (RUNCOMMAND_USER + GETFILENAMEATCURSOR)

#define FULL_CURRENT_PATH      1
#define CURRENT_DIRECTORY      2
#define FILE_NAME              3
#define NAME_PART              4
#define EXT_PART               5
#define CURRENT_WORD           6
#define NPP_DIRECTORY          7
#define GETFILENAMEATCURSOR    8

#define VAR_NOT_RECOGNIZED     0
#define FULL_CURRENT_PATH_CMD  1
#define CURRENT_DIRECTORY_CMD  2
#define FILE_NAME_CMD          3
#define NAME_PART_CMD          4
#define EXT_PART_CMD           5
#define CURRENT_WORD_CMD       6
#define NPP_DIRECTORY_CMD      7
#define GETFILENAMEATCURSOR_CMD 8

#define SCINTILLA_USER   (WM_USER + 2000)
#define SCI_START 2000
#define SCI_OPTIONAL_START 3000
#define SCI_LEXER_START 4000

#define NPPN_FIRST            1000
#define NPPN_READY            (NPPN_FIRST + 1)
#define NPPN_TBMODIFICATION   (NPPN_FIRST + 2)
#define NPPN_FILEBEFORECLOSE  (NPPN_FIRST + 3)
#define NPPN_FILEOPENED       (NPPN_FIRST + 4)
#define NPPN_FILECLOSE        (NPPN_FIRST + 6)
#define NPPN_FILECLOSED       (NPPN_FIRST + 7)
#define NPPN_FILEBEFOREOPEN   (NPPN_FIRST + 8)
#define NPPN_FILEBEFORESAVE   (NPPN_FIRST + 9)
#define NPPN_FILESAVED        (NPPN_FIRST + 10)
#define NPPN_SHUTDOWN         (NPPN_FIRST + 11)
#define NPPN_BUFFERACTIVATED  (NPPN_FIRST + 12)
#define NPPN_LANGCHANGED      (NPPN_FIRST + 13)
#define NPPN_WORDSTYLESUPDATED    (NPPN_FIRST + 14)
#define NPPN_SHORTCUTREMAPPED     (NPPN_FIRST + 15)
#define NPPN_FILEBEFORELOAD       (NPPN_FIRST + 16)
#define NPPN_FILELOADFAILED       (NPPN_FIRST + 17)
#define NPPN_READONLYCHANGED      (NPPN_FIRST + 18)
#define NPPN_DOCORDERCHANGED      (NPPN_FIRST + 19)
#define NPPN_SNAPSHOTDIRTYFILELOADED (NPPN_FIRST + 20)
#define NPPN_BEFORESHUTDOWN          (NPPN_FIRST + 21)
#define NPPN_CANCELSHUTDOWN          (NPPN_FIRST + 22)
#define NPPN_FILEBEFORERENAME        (NPPN_FIRST + 23)
#define NPPN_FILERENAMECANCEL        (NPPN_FIRST + 24)
#define NPPN_FILERENAMED             (NPPN_FIRST + 25)
#define NPPN_FILEBEFOREDELETE        (NPPN_FIRST + 26)
#define NPPN_FILEDELETEFAILED        (NPPN_FIRST + 27)
#define NPPN_FILEDELETED             (NPPN_FIRST + 28)
#define NPPN_DARKMODECHANGED         (NPPN_FIRST + 29)

#endif //NOTEPAD_PLUS_MSGS_H
